name: Test package
on:
  pull_request:
  push:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: clean-install
        run: npm ci

      - name: lint check
        run: npm run lint

      - name: build
        run: npm run build
